#!/usr/bin/env python

import sys
from rqt_gui.main import Main
from rqt_qml.plugin import QMLPlugin


plugin = 'rqt_qml.plugin.QMLPlugin'
main = Main(filename=plugin)
sys.exit(main.main(standalone=plugin, plugin_argument_provider=QMLPlugin.add_arguments))
